#Compile Block https://github.com/esphome/esphome/pull/4874 #https://github.com/epiclabs-uc/esphome-modbus-server
esphome:
  name: esp-sensors
  friendly_name: ESP Sensors

packages:
  external_components.bthome: !include pkg/sources/bthome.yaml
  external_components.modbus: !include pkg/sources/modbus_server.yaml
  metric: !include pkg/metric.yaml
  basic: !include pkg/basic.yaml  
  ble: !include pkg/ble.yaml

wifi:
  domain: ".iot.cloud-lab.xyz"

api:
  encryption:
    key: "mY2PuxeI7kVcAZIITrg+sOE6UOCP1TYNmWBdlmjxP94="

web_server:
  port: 80

uart:
  - id: intmodbus
    tx_pin: 17
    rx_pin: 16
    baud_rate: 115200
    stop_bits: 1
    data_bits: 8
    parity: NONE
    debug:
      direction: BOTH  
      
modbus_server:
  - id: modbuserver
    uart_id: intmodbus
    address: 1 # slave address
    holding_registers:
      - start_address: 100 # in this example we map register 200 to a switch
        number: 1
        on_read: |-
          return 0x0164;    
# bthome_ble_receiver:  

# #Sensors
# sensor:
#   #A4:C1:38:3D:B4:56
#   - platform: bthome_ble_receiver
#     mac_address: "A4:C1:38:3D:B4:56"
#     sensors:
#       - measurement_type: temperature
#         id: ATC_3DB456_temperature
#         name: ESP_ATC_3DB456
#   #A4:C1:38:4B:F5:95
#   - platform: bthome_ble_receiver
#     mac_address: "A4:C1:38:4B:F5:95"
#     sensors:
#       - measurement_type: temperature
#         id: ATC_4BF595_temperature
#         name: ESP_ATC_4BF595
#   #A4:C1:38:BB:95:0A
#   - platform: bthome_ble_receiver
#     mac_address: "A4:C1:38:BB:95:0A"
#     sensors:
#       - measurement_type: temperature
#         id: ATC_BB950A_temperature
#         name: ESP_ATC_BB950A
#   #A4:C1:38:73:97:8C
#   - platform: bthome_ble_receiver
#     mac_address: "A4:C1:38:73:97:8C"
#     sensors:
#       - measurement_type: temperature
#         id: ATC_73978C_temperature
#         name: ESP_ATC_73978C
#   #A4:C1:38:F6:19:41
#   - platform: bthome_ble_receiver
#     mac_address: "A4:C1:38:F6:19:41"
#     sensors:
#       - measurement_type: temperature
#         id: ATC_F61941_temperature
#         name: ESP_ATC_F61941
#   #A4:C1:38:F6:19:41
#   - platform: bthome_ble_receiver
#     mac_address: "A4:C1:38:B7:55:95"
#     sensors:
#       - measurement_type: temperature
#         id: ATC_B75595_temperature
#         name: ESP_ATC_B75595
