#Compile Block https://github.com/esphome/esphome/pull/4874 #https://github.com/epiclabs-uc/esphome-modbus-server
esphome:
  name: esp-ds1820
  friendly_name: ESP DS1820 Test


packages:
  metric: !include pkg/metric.yaml
  basic: !include pkg/basic.yaml  

api:
  encryption:
    key: "mY2PuxeI7kVcAZIITrg+sOE6UOCP1TYNmWBdlmjxP94="

web_server:
  port: 80

dallas:
  - pin: 4
    id: main_ds
    update_interval: 10s

# Individual sensors
sensor:
  - platform: dallas
    dallas_id: main_ds
    address: 0x7508cf7d1f64ff28
    resolution: 12
    accuracy_decimals: 2
    name: "Test Dalas"
