#Generic Block
esphome:
  name: esp-termo
  friendly_name: ESP Ectocontrol Thermostat



packages:
  external_components.bthome: !include pkg/sources/bthome.yaml
  metric: !include pkg/metric.yaml
  basic: !include pkg/basic.yaml  
  ble: !include pkg/ble.yaml
  pid.ecto: !include {file: pkg/pid/climate.yaml, vars: { pid_id: pid_ecto, zone_name: 1, short_mac: 3DB456} }   

wifi:
  domain: ".iot.cloud-lab.xyz"
   
api:
  encryption:
    key: "mY2PuxeI7kVcAZIITrg+sOE6UOCP1TYNmWBdlmjxP94="

#web_server:
#  port: 80

bthome_ble_receiver:  

binary_sensor:
  # In case the API connection is lost, the controller will change
  # to automatic mode.
  - platform: template
    id: sensor_api_connected
    name: Autonomous Mode
    lambda: return !global_api_server->is_connected();
    filters:
      - delayed_off: 60s

sensor:
  #A4:C1:38:3D:B4:56
  - platform: bthome_ble_receiver
    mac_address: "A4:C1:38:3D:B4:56"
    sensors:
      - measurement_type: temperature
        id: modbus_ATC_3DB456
        name: main-sens

switch:
  - <<: !include { file: tpl/gpio_switch.yaml, vars: { pin_number: 23, switch_id: valve_zone1_switch } }            
  # - <<: !include { file: tpl/gpio_switch.yaml, vars: { pin_number: 22, switch_id: valve2_switch } }            
  # - <<: !include { file: tpl/gpio_switch.yaml, vars: { pin_number: 21, switch_id: valve3_switch } }              
  # - <<: !include { file: tpl/gpio_switch.yaml, vars: { pin_number: 19, switch_id: valve4_switch } }              
  # - <<: !include { file: tpl/gpio_switch.yaml, vars: { pin_number: 18, switch_id: valve5_switch } }              
  # - <<: !include { file: tpl/gpio_switch.yaml, vars: { pin_number: 4, switch_id: valve6_switch } }              
  # - <<: !include { file: tpl/gpio_switch.yaml, vars: { pin_number: 13, switch_id: boiler_switch } }               
