sensor:
  # FREE Heap Sensor
  - platform: template
    name: Free HEAP
    id: free_heap
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL);
    icon: "mdi:memory"
    entity_category: diagnostic
    state_class: measurement
    unit_of_measurement: "b"
    update_interval: 60s
  # Uptime Sensor
  - platform: uptime
    name: Uptime
    id: esp_uptime
  # FREE Mem Sensor
  - platform: debug
    free:
      name: Free MEM
      id: free_mem